import { TableEntry } from "../ui/components/TableComponent/TableComponent.types";

const tableData1: TableEntry[] = [
  {
    lotNumber: "72a7f9d0",
    wineName: "TestWine",
    origin: "Bolnisi A",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 2,
    status: "FINALISED",
  },
  {
    lotNumber: "72a7f9d1",
    wineName: "TestWine",
    origin: "Bolnisi B",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 12,
    status: "NOT_FINALISED",
  },
  {
    lotNumber: "72a7f9d2",
    wineName: "TestWine",
    origin: "Bolnisi B",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 70,
    status: "NOT_FINALISED",
  },
  {
    lotNumber: "72a7f9d3",
    wineName: "TestWine",
    origin: "Bolnisi C",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 654,
    status: "NOT_FINALISED",
  },
  {
    lotNumber: "72a7f9d4",
    wineName: "TestWine",
    origin: "Bolnisi D",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 26,
    status: "NOT_FINALISED",
  },
  {
    lotNumber: "72a7f9d5",
    wineName: "TestWine",
    origin: "Bolnisi E",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 26,
    status: "NOT_FINALISED",
  },
  {
    lotNumber: "72a7f9d6",
    wineName: "TestWine",
    origin: "Bolnisi F",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 72,
    status: "APPROVED",
  },
];
const tableData2: TableEntry[] = [
  {
    lotNumber: "72a7f9d1",
    wineName: "TestWine",
    origin: "Bolnisi A",
    countryOfOrigin: "Georgia",
    producedBy: "Winery 2A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 2,
    status: "FINALISED",
  },
  {
    lotNumber: "72a7f9d2",
    wineName: "TestWine",
    origin: "Bolnisi B",
    countryOfOrigin: "Georgia",
    producedBy: "Winery 2B",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 22,
    status: "FINALISED",
  },
  {
    lotNumber: "72a7f9d3",
    wineName: "TestWine",
    origin: "Bolnisi C",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 22,
    status: "FINALISED",
  },
  {
    lotNumber: "72a7f9d4",
    wineName: "TestWine",
    origin: "Bolnisi D",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 22,
    status: "FINALISED",
  },
  {
    lotNumber: "72a7f9d5",
    wineName: "TestWine",
    origin: "Bolnisi E",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 22,
    status: "FINALISED",
  },
  {
    lotNumber: "72a7f9d6",
    wineName: "TestWine",
    origin: "Bolnisi F",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 22,
    status: "FINALISED",
  },
  {
    lotNumber: "72a7f9d7",
    wineName: "TestWine",
    origin: "Bolnisi G",
    countryOfOrigin: "Georgia",
    producedBy: "Winery A",
    producerAddress: "Bolnisi, Georgia",
    producerLatitude: "42.1237",
    producerLongitude: "42.8962975",
    varietalName: "Variety A",
    vintageYear: "2022",
    wineType: "Dry",
    wineColor: "Red",
    harvestDate: "2022-10-05",
    harvestLocation: "Bolnisi, Georgia",
    pressingDate: "2022-10-06",
    processingLocation: "Bolnisi, Georgia",
    fermentationVessel: "Qvevri",
    fermentationDuration: "2 months",
    agingRecipient: "Recipient",
    agingTime: "2 months",
    storageVessel: "Steel container",
    bottlingDate: "2022-10-07",
    bottlingLocation: "Bolnisi, Georgia",
    numberOfBottles: 72,
    status: "APPROVED",
  },
];

export { tableData1, tableData2 };
