name: PR builds

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  buildJava:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Test
        run: ./mvnw --batch-mode --update-snapshots clean package --file ./pom.xml

  buildFrontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run unit tests
        run: |
          npm ci --prefix frontend
          npm test --prefix frontend

      - name: 🔨 Build project
        run: npm run build --prefix frontend

  buildMobile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run unit tests
        run: |
          npm ci --prefix mobileapp
          npm test --prefix mobileapp

      - name: 🔨 Build project
        run: npm run build:cap --prefix mobileapp
